### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by tali** [google/safevalues#212]
Safari (version 16) does not support [TrustedTypes](https://caniuse.com/mdn-api_trustedtypes) and `safevalues` thus falls back to its own implementation (`HtmlImpl`).
But `HtmlImpl` is only working in nodejs environments as it checks for an environment variable via `process.env` (see [html_impl.ts:20](https://github.com/google/safevalues/blob/main/src/internals/html_impl.ts#L20))
When using `safevalues` in Safari, this only leads to the error message 'ReferenceError: Can't find variable: process'.

**Comment by neuracr** [comment]
Thanks for reporting.  
Do you have a link to a reproducer?

The intended behavior depends on the webpack mode (https://webpack.js.org/guides/production/#specify-the-mode):
 - In 'production' mode, the [html_impl.ts:20](https://github.com/google/safevalues/blob/main/src/internals/html_impl.ts#L20) block should be optimized away, as well as the [dev.ts](https://github.com/google/safevalues/blob/main/src/environment/dev.ts)
 - In anything else than 'production', [dev.ts](https://github.com/google/safevalues/blob/main/src/environment/dev.ts) sets the `process` variable when it's not running in Node. The block in [html_impl.ts:20](https://github.com/google/safevalues/blob/main/src/internals/html_impl.ts#L20) is not optimized away.

I've found https://github.com/pahund/webpack-devprod-experiment which does a similar thing.

**Comment by tali** [comment]
I found this problem in Gerrit master, which now uses `safevalues`.
Gerrit uses rollup instead of webpack, but when I use `rollup-plugin-define` for `process.env.NODE_ENV` then it works as intended again.
Thanks for the help!
