### ISSUE TITLE
allowPartAttributes?

### ISSUE THREAD

**Issue by tushuhei** [google/safevalues#256]
In the context of Web Components, `part` attributes are used to apply styles to the items under an open shadow DOM.
Having an option to allow `part` attributes for the Sanitizer Builder API would be helpful to make the sanitizer work with custom elements.
I thought the carried risk would be similar to `allowClassAttributes`, but I would love to hear your thoughts.

**Comment by neuracr** [comment]
Could you share more context on your use case?  
Where is the HTML coming from? Is it user controlled?

We are generally trying to better understand the use cases of our users, and we don't have a lot of feedback on custom elements.

I agree the risk should be similar to the class attributes.

**Comment by tushuhei** [comment]
My usecase is around a project called [BudouX](https://github.com/google/budoux). It's a word segmenter library for Asian languages that don't have word delimiters like Latin languages. It has a custom element `<budoux-ja>` that inserts `<wbr>` tags to the given HTML snippet to provide proper line breaking opportunities. The conversion is done by parsing the given HTML and outputting the result to the shadow dom.
https://github.com/google/budoux/blob/main/javascript/src/webcomponents/budoux-base.ts

In order to keep the control over the converted output under the shadow dom, retaining `part` attributes would be preferred. The following example shows how `part` attributes will be used. 
https://codepen.io/tushuhei/pen/WNgdzYw

The HTML can be come from a trusted source or user inputs depending on how the developer uses the BudouX Web Component in their website.

**Comment by engelsdamien** [comment]
Sorry for the slow response, @neuracr is currently out of office, so I will attempt to help:

Have you considered directly building a `DomFragment` instead of returning strings from your parser ?
This would allow you to avoid unnecessary serialization/parsing/sanitization steps.

Something like this:

```typescript
// in dom.ts
function parseFromString(html: string): Node {
  const template = document.createElement('template');
  template.innerHTML = html;
  return template.content;
}

// parser.ts
function translateHTMLString(html: string): Node {
  if (html === '') return new DocumentFragment();
  const fragment = parseFromString(html);
  if (Parser.hasChildTextNode(fragment)) {
    const wrapper = document.createElement('span');
    wrapper.append(...fragment.childNodes);
    fragment.appendChild(wrapper);
  }
  this.applyElement(fragment.firstChild as HTMLElement);
  return fragment;
}

// in budoux-base.ts
sync() {
  const translated = this.parser.translateHTMLString(this.innerHTML);
  this.shadow.textContent = '';
  this.shadow.appendChild(translated);
}
```

You can even avoid having to parse anything at all if you clone the existing nodes instead of grabbing `this.innerHTML`.

```typescript
// in budoux-base.ts
sync() {
  let translated: HTMLElement;
  if (Parser.hasChildTextNode(this)) {
    translated = document.createElement('span');
    translated.append(...this.childNodes.map(node => node.cloneNode(true)));
  } else {
    translated = this.firstElementChild!.cloneNode(true) as HTMLElement;
  }

  this.parser.applyElement(translated);

  this.shadow.textContent = '';
  this.shadow.appendChild(translated);
}
```

This is also likely to be more performant than parsing and serializing the tree multiple times.

**Comment by tushuhei** [comment]
Sorry for my late reply.
Thanks for your suggestions! Let me follow up on this at https://github.com/google/budoux/issues/273

That being said, I believe this won't resolve the issue that the elements inside the shadow element are not stylizable from outside. Of course this is by design of a shadow element, but allowing `part` attributes will provide a workaround for users to control the style from outside for specific elements, as shown in [my demo](https://codepen.io/tushuhei/pen/WNgdzYw).

**Comment by tushuhei** [comment]
Thanks again for your insightful suggestions on using DomFragment. Since we've switched to Light DOMs and no longer need to worry about shadow DOM styling limitations, I'm closing this issue.
