### ISSUE TITLE
How to allow <iframe> while sanitize html string

### ISSUE THREAD

**Issue by indrasenakatam** [google/safevalues#446]
import {sanitizeHtml} from 'safevalues';

before sanitizeHtml
```
<div> some text </div>
<div>
<iframe 
title="Google Fiber: Find your Fiber Jack" 
src="[https://www.youtube.com/embed/XXXXX"](https://www.youtube.com/embed/XXXXX%22)
width="300" height="300" 
frameborder="0" 
allowfullscreen="allowfullscreen">
</iframe>
</div>
```

after sanitizeHtml
` <div>some text</div>\n<div></div>`

could you please suggest if there any way to allow iframe tag after Sanitization. 

thank you in advance.

**Comment by engelsdamien** [comment]
Our sanitizer doesn't support iframes for dynamically sanitized html, this is unfortunately not configurable.

Note that if your html is not dynamic/user-provided, you should probably use a templating system.
