### ISSUE TITLE
Jest is failing after SafeValues changed from "commonjs" to "es2015"

### ISSUE THREAD

**Issue by danrevah** [google/safevalues#65]
Getting an error after updating Safevalues to version `0.1.5`:
```
    safevalues-import/node_modules/safevalues/unsafe/reviewed.js:17
    import { createHtml } from '../implementation/html_impl';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

Reproduction in repo:
https://github.com/danrevah/safevalues-import

Running `npm test` would fail.

**Comment by sebastianjnuwu** [comment]
one year

**Comment by danrevah** [comment]
you could use `transform` and `transformIgnorePatterns` to have ES6 modules supported with jest.

Following example works with the previous reproduction repository:

```
module.exports = {
  transform: {
    [`(safevalues).+\\.js$`]: 'ts-jest',
    [`^.+\\.tsx?$`]: 'ts-jest',
  },
  transformIgnorePatterns: [`/node_modules/(?!safevalues)`],
  testMatch: ['**/*.spec.[jt]s?(x)'],
  moduleFileExtensions: ['js', 'ts'],
}
```

**Comment by neuracr** [comment]
Thanks Dan,
I have updated safevalues to package both a CommonJS and an ES module, starting from version 0.3.2.  
When depending on safevalues, Node should pick the correct module format automatically.
